
export const ROLE_GROUPS = {
    // Super-admin only tier (destructive / privilege-granting operations)
    SUPER_ADMINS: ['SUPER_ADMIN'],
    // Core administration pair
    CORE_ADMINS: ['SUPER_ADMIN', 'ADMIN'],

    // Executive Leadership Tier
    EXECUTIVES: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP'],
    ADMINS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP'],
    OPS: ['OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'QC_OFFICER'],

    // Department Roles (From sidebar-menu)
    SOD_PROJECT: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'QC_OFFICER'],
    SA_PROJECT: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'SA_MANAGER', 'SA_ASSISTANT', 'FAULT_COORDINATOR', 'REPAIR_TECHNICIAN'],
    OSP_PROJECTS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'OSP_ENGINEER', 'CIVIL_SUPERVISOR', 'CABLE_SPLICER', 'ENGINEER'],
    FINANCE: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'FINANCE_MANAGER', 'FINANCE_ASSISTANT', 'CASHIER'],
    STORES: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'STORES_MANAGER', 'STORES_ASSISTANT'],
    SF_INVOICING: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'INVOICE_MANAGER', 'INVOICE_ASSISTANT', 'AR_OFFICER'],
    INVOICE: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'INVOICE_MANAGER', 'INVOICE_ASSISTANT', 'AR_OFFICER'],
    SF_AUDITING: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'SF_AUDIT_MANAGER', 'SF_AUDIT_OFFICER', 'RATE_AUDITOR', 'FINANCE_MANAGER'],
    PROCUREMENT: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'PROCUREMENT_OFFICER'],
    NEW_CONNECTION: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER'],
    SERVICE_ASSURANCE: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'SA_MANAGER', 'SA_ASSISTANT'],
    ALL_OPS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'QC_OFFICER', 'SA_MANAGER', 'SA_ASSISTANT', 'OSP_ENGINEER'],

    // Presets for cross-functional operations
    FINANCE_APPROVERS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'FINANCE_MANAGER', 'STORES_MANAGER'],
    FINANCE_ALL: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'FINANCE_MANAGER', 'FINANCE_ASSISTANT'],
    STORES_MANAGERS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'STORES_MANAGER', 'HEAD_OF_OSP'],
    STORES_ALL: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'STORES_MANAGER', 'STORES_ASSISTANT'],
    PROJECT_MANAGERS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'MANAGER', 'OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER'],
    MATERIAL_REQUESTERS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'STORES_MANAGER', 'STORES_ASSISTANT', 'PROCUREMENT_OFFICER', 'CONTRACTOR_SUPERVISOR'],
    PURCHASE_ORDER_MANAGERS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'MANAGER', 'OSP_MANAGER', 'AREA_MANAGER', 'PROCUREMENT_OFFICER'],
    AREA_MANAGERS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'AREA_MANAGER'],
    SF_AUDITORS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'FINANCE_MANAGER', 'SF_AUDIT', 'SF_AUDIT_OFFICER', 'SF_AUDIT_MANAGER'],
    OFFICE_ADMINS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'OFFICE_ADMIN', 'OFFICE_ADMIN_ASSISTANT', 'SITE_OFFICE_STAFF'],
    CONTRACTORS: ['SUPER_ADMIN', 'ADMIN', 'CEO', 'CONTRACTOR_SUPERVISOR', 'CONTRACTOR_TECHNICIAN', 'CONTRACTOR_FINANCE'],

    // Contractor data read scopes
    CONTRACTOR_READERS: [
        'SUPER_ADMIN', 'ADMIN', 'OFFICE_ADMIN', 'OFFICE_ADMIN_ASSISTANT',
        'OSP_MANAGER', 'AREA_MANAGER', 'FINANCE_MANAGER', 'FINANCE_ASSISTANT',
        'SITE_OFFICE_STAFF', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR',
        'MANAGER', 'QC_OFFICER', 'STORES_MANAGER', 'STORES_OFFICER',
        'CONTRACTOR_SUPERVISOR', 'CONTRACTOR_TECHNICIAN', 'CONTRACTOR_FINANCE', 'CONTRACTOR'
    ],
    CONTRACTOR_TEAM_READERS: [
        'SUPER_ADMIN', 'ADMIN', 'OFFICE_ADMIN', 'OFFICE_ADMIN_ASSISTANT',
        'OSP_MANAGER', 'AREA_MANAGER', 'FINANCE_MANAGER', 'FINANCE_ASSISTANT',
        'SITE_OFFICE_STAFF', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR',
        'MANAGER', 'QC_OFFICER'
    ],
};

export type RoleGroup = keyof typeof ROLE_GROUPS;

export function hasRole(userRole: string | undefined | null, roleGroup: string[]): boolean {
    if (!userRole) return false;
    return roleGroup.includes(userRole);
}
