
export const ROLE_GROUPS = {
    ADMINS: ['SUPER_ADMIN', 'ADMIN'],
    STORES: ['STORES_MANAGER', 'STORES_ASSISTANT'],
    OPS: ['OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'QC_OFFICER'],
    FINANCE: ['FINANCE_MANAGER', 'FINANCE_ASSISTANT'],
    INVOICE: ['INVOICE_MANAGER', 'INVOICE_ASSISTANT'],
    OFFICE: ['OFFICE_ADMIN', 'OFFICE_ADMIN_ASSISTANT', 'SITE_OFFICE_STAFF']
};

export type RoleGroup = keyof typeof ROLE_GROUPS;
