
export const ROLE_GROUPS = {
    ADMINS: ['SUPER_ADMIN', 'ADMIN'],
    STORES: ['STORES_MANAGER', 'STORES_ASSISTANT'],
    OPS: ['OSP_MANAGER', 'AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'QC_OFFICER'],
    FINANCE: ['FINANCE_MANAGER', 'FINANCE_ASSISTANT'],
    INVOICE: ['INVOICE_MANAGER', 'INVOICE_ASSISTANT'],
    OFFICE: ['OFFICE_ADMIN', 'OFFICE_ADMIN_ASSISTANT', 'SITE_OFFICE_STAFF'],

    // Presets for cross-functional operations
    FINANCE_APPROVERS: ['SUPER_ADMIN', 'ADMIN', 'FINANCE_MANAGER'],
    FINANCE_ALL: ['SUPER_ADMIN', 'ADMIN', 'FINANCE_MANAGER', 'FINANCE_ASSISTANT'],
    STORES_MANAGERS: ['SUPER_ADMIN', 'ADMIN', 'STORES_MANAGER'],
    STORES_ALL: ['SUPER_ADMIN', 'ADMIN', 'STORES_MANAGER', 'STORES_ASSISTANT'],
    PROJECT_MANAGERS: ['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'OSP_MANAGER', 'AREA_MANAGER'],
    SF_AUDITORS: ['SUPER_ADMIN', 'ADMIN', 'FINANCE_MANAGER', 'SF_AUDIT', 'SF_AUDIT_OFFICER', 'SF_AUDIT_MANAGER'],
    OFFICE_ADMINS: ['SUPER_ADMIN', 'ADMIN', 'OFFICE_ADMIN'],
};

export type RoleGroup = keyof typeof ROLE_GROUPS;
