export const ROLE_CATEGORIES = {
    'System Admin': ['SUPER_ADMIN', 'ADMIN'],
    'Main Management': ['CEO', 'HEAD_OF_OSP', 'OSP_MANAGER', 'MANAGER'],
    'OSP & Operations': ['AREA_MANAGER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'AREA_COORDINATOR', 'QC_OFFICER', 'OSP_ENGINEER', 'CIVIL_SUPERVISOR', 'CABLE_SPLICER'],
    'Stores & Inventory': ['STORES_MANAGER', 'STORES_ASSISTANT'],
    'Finance': ['FINANCE_MANAGER', 'FINANCE_ASSISTANT', 'AR_OFFICER'],
    'Invoice Section': ['INVOICE_MANAGER', 'INVOICE_ASSISTANT'],
    'Service Assurance': ['SA_MANAGER', 'SA_ASSISTANT', 'FAULT_COORDINATOR', 'REPAIR_TECHNICIAN'],
    'SF Audit Section': ['SF_AUDIT_MANAGER', 'SF_AUDIT_OFFICER', 'RATE_AUDITOR'],
    'Office Admin': ['OFFICE_ADMIN', 'OFFICE_ADMIN_ASSISTANT', 'SITE_OFFICE_STAFF'],
    'Procurement': ['PROCUREMENT_OFFICER']
};

export type RoleCategory = keyof typeof ROLE_CATEGORIES;
