import { Prisma } from '@prisma/client';
import { LedgerService } from './ledger.service';
import { AppError } from '@/lib/error';
import type { TransactionClient } from '@/types/inventory/inventory-service.types';

export class OSPLedgerService {
  /**
   * Automatically resolves GL Mappings and posts a Subledger event to the Unified Ledger.
   */
  static async postAutomatedTransaction(
    tx: TransactionClient,
    args: {
      sourceModule: string;
      transactionType: string;
      referenceId: string;
      description: string;
      amount: number;
      transactionDate: Date;
    }
  ) {
    // 1. Look up mapping
    const mapping = await tx.gLMappingConfig.findUnique({
      where: {
        sourceModule_transactionType: {
          sourceModule: args.sourceModule,
          transactionType: args.transactionType,
        }
      }
    });

    if (!mapping || !mapping.isActive) {
      // Fail loud: a subledger event must never silently bypass the ledger.
      // A missing/inactive mapping means the GL configuration is incomplete
      // (see scripts/seed-all-financial-gl.ts) and posting cannot proceed.
      throw AppError.badRequest(
        `No active GL mapping configured for ${args.sourceModule}:${args.transactionType}. ` +
        `Seed the required GLMappingConfig before posting this subledger event.`
      );
    }

    // 2. Post to Unified Ledger via LedgerService
    return await LedgerService.postTransaction(tx, {
      referenceId: args.referenceId,
      referenceType: args.sourceModule,
      description: args.description,
      date: args.transactionDate,
      isAutoGenerated: true,
      lines: [
        {
          accountCode: mapping.debitAccountCode,
          debit: args.amount,
          credit: 0,
          description: `DR: ${args.description}`
        },
        {
          accountCode: mapping.creditAccountCode,
          debit: 0,
          credit: args.amount,
          description: `CR: ${args.description}`
        }
      ]
    });
  }
}
