/**
 * SLT-ERP Bridge build helper.
 *
 * Everything that needs real crypto or Chrome's own packer lives here so the
 * PowerShell installer stays a thin orchestrator. Chrome/Edge only accept a
 * policy-installed extension when a CRX3 package and a Google-update-protocol
 * XML agree on the extension id, and that id is derived from the signing key -
 * which is exactly the part no shell script should guess at.
 *
 * Usage:
 *   node scripts/extension/build-bridge.mjs id
 *   node scripts/extension/build-bridge.mjs updates-xml [--base-url <url>]
 *   node scripts/extension/build-bridge.mjs pack-crx
 *   node scripts/extension/build-bridge.mjs firefox-manifest --out <dir>
 *   node scripts/extension/build-bridge.mjs info
 */
import { createHash, createPublicKey } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const EXT_DIR = path.join(ROOT, 'public', 'slt-bridge');
const PEM_FILE = path.join(ROOT, 'public', 'slt-bridge.pem');
const CRX_FILE = path.join(ROOT, 'public', 'slt-bridge.crx');
const XML_FILE = path.join(ROOT, 'public', 'slt-bridge-updates.xml');
const DEFAULT_BASE_URL = 'https://sltserp.vercel.app';
/** Stable Firefox id - changing it later orphans every existing install. */
const GECKO_ID = process.env.BRIDGE_GECKO_ID || 'slt-erp-bridge@slts.lk';

function readManifest() {
    const raw = fs.readFileSync(path.join(EXT_DIR, 'manifest.json'), 'utf8');
    return /** @type {{ version: string, name: string }} */ (JSON.parse(raw));
}

/**
 * Chromium derives the extension id from the subject public key: sha-256 over
 * the DER/SPKI encoding, first 16 bytes, each nibble mapped onto a-p.
 */
function extensionIdFromPem(pemPath = PEM_FILE) {
    if (!fs.existsSync(pemPath)) {
        throw new Error(`Signing key not found: ${pemPath}`);
    }
    const key = createPublicKey(fs.readFileSync(pemPath));
    const spki = key.export({ type: 'spki', format: 'der' });
    const digest = createHash('sha256').update(spki).digest().subarray(0, 16);
    return [...digest]
        .map((byte) => `${String.fromCharCode(97 + (byte >> 4))}${String.fromCharCode(97 + (byte & 15))}`)
        .join('');
}

function writeUpdatesXml(baseUrl) {
    const manifest = readManifest();
    const id = extensionIdFromPem();
    const url = `${baseUrl.replace(/\/+$/, '')}/slt-bridge.crx`;
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Self-hosted update manifest for Chrome/Edge ExtensionInstallForcelist.
     Generated by scripts/extension/build-bridge.mjs - do not hand edit. -->
<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
  <app appid="${id}">
    <updatecheck codebase="${url}" version="${manifest.version}" package="${id}.crx" />
  </app>
</gupdate>
`;
    fs.writeFileSync(XML_FILE, xml, 'utf8');
    return { id, version: manifest.version, crxUrl: url, file: XML_FILE };
}

function findChrome() {
    const candidates = [
        process.env.CHROME_PATH,
        'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
        'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        path.join(process.env.LOCALAPPDATA ?? '', 'Google\\Chrome\\Application\\chrome.exe'),
        'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    ].filter((c) => typeof c === 'string' && c.length > 0);
    return candidates.find((c) => fs.existsSync(c)) ?? null;
}

/**
 * Reads the CRX header: "Cr24" magic + 4-byte little-endian format version.
 * Chrome 86+ refuses CRX2 entirely, so a policy install needs this to say 3.
 */
function crxFormat(file = CRX_FILE) {
    const buf = fs.readFileSync(file);
    if (buf.subarray(0, 4).toString('latin1') !== 'Cr24') return 0;
    return buf.readUInt32LE(4);
}

function packCrx() {
    const chrome = findChrome();
    if (!chrome) {
        console.error('No Chrome/Edge binary found - install Chrome or pass $env:CHROME_PATH.');
        process.exitCode = 1;
        return;
    }
    const profile = path.join(os.tmpdir(), 'slt-bridge-pack');
    // Chrome writes <dir>.crx next to the packed folder, i.e. public/slt-bridge.crx.
    execFileSync(chrome, [
        `--pack-extension=${EXT_DIR}`,
        `--pack-extension-key=${PEM_FILE}`,
        `--user-data-dir=${profile}`,
        '--no-first-run',
        '--no-default-browser-check',
    ], { stdio: 'inherit' });

    if (!fs.existsSync(CRX_FILE)) {
        console.error('Packing produced no .crx - is another Chrome instance holding the profile?');
        process.exitCode = 1;
        return;
    }
    const format = crxFormat();
    console.log(`Packed ${path.relative(ROOT, CRX_FILE)} (${fs.statSync(CRX_FILE).size} bytes, CRX${format})`);
    if (format !== 3) {
        console.error('CRX3 expected - Chrome/Edge will refuse this package for policy installs.');
        process.exitCode = 1;
    }
}

/**
 * Returns true for http:// / https:// / *:// match patterns that point at
 * localhost or 127.0.0.1. These dev-only entries live in the source manifest
 * but must NOT ship in store upload packages (CWS / Edge Add-ons / AMO reject
 * them). The source manifest itself is never modified.
 */
const isLocalDevPattern = (p) => /^(http|https|\*):\/\/(localhost|127\.0\.0\.1)(:[0-9]+)?(\/|$|\*)/.test(p);

/**
 * Firefox cannot run an MV3 service worker, and it needs an explicit add-on id.
 * Everything else in the bridge (storage/tabs/cookies/alarms + the chrome.* alias)
 * is already portable, so only the manifest is patched.
 */
function writeFirefoxManifest(outDir, geckoId) {
    const manifest = { ...readManifest() };
    const worker = String(manifest.background?.service_worker ?? 'background.js');
    manifest.background = { scripts: [worker], persistent: false };
    manifest.browser_specific_settings = {
        gecko: { id: geckoId, strict_min_version: '128.0' },
    };
    // Strip dev-only localhost match patterns from the AMO upload package
    // (same policy as the Chromium CWS zip; source manifest keeps them).
    if (Array.isArray(manifest.host_permissions)) {
        manifest.host_permissions = manifest.host_permissions.filter((p) => !isLocalDevPattern(p));
    }
    if (Array.isArray(manifest.content_scripts)) {
        manifest.content_scripts = manifest.content_scripts.map((cs) => ({
            ...cs,
            matches: (cs.matches ?? []).filter((p) => !isLocalDevPattern(p)),
        }));
    }
    if (Array.isArray(manifest.web_accessible_resources)) {
        manifest.web_accessible_resources = manifest.web_accessible_resources.map((war) => ({
            ...war,
            matches: (war.matches ?? []).filter((p) => !isLocalDevPattern(p)),
        }));
    }
    fs.mkdirSync(outDir, { recursive: true });
    const target = path.join(outDir, 'manifest.json');
    fs.writeFileSync(target, `${JSON.stringify(manifest, null, 4)}\n`, 'utf8');
    return target;
}

function info() {
    const manifest = readManifest();
    console.log(JSON.stringify({
        version: manifest.version,
        extensionId: extensionIdFromPem(),
        source: path.relative(ROOT, EXT_DIR),
        crx: fs.existsSync(CRX_FILE) ? `${fs.statSync(CRX_FILE).size}b CRX${crxFormat()}` : 'missing',
        updateXml: fs.existsSync(XML_FILE) ? path.relative(ROOT, XML_FILE) : 'missing',
    }, null, 2));
}

function arg(flag, fallback) {
    const i = process.argv.indexOf(flag);
    return i > -1 ? process.argv[i + 1] : fallback;
}

const command = process.argv[2] ?? 'info';
switch (command) {
    case 'id':
        console.log(extensionIdFromPem());
        break;
    case 'info':
        info();
        break;
    case 'pack-crx':
        packCrx();
        break;
    case 'updates-xml':
        console.log(JSON.stringify(writeUpdatesXml(arg('--base-url', DEFAULT_BASE_URL)), null, 2));
        break;
    case 'firefox-manifest': {
        const out = arg('--out', path.join(EXT_DIR, '..', 'slt-bridge-firefox'));
        console.log(writeFirefoxManifest(out, arg('--gecko-id', GECKO_ID)));
        break;
    }
    default:
        console.error(`Unknown command: ${command}`);
        process.exitCode = 1;
}
