/**
 * Dynamic Trigger Sync
 * 
 * Reads prisma/triggers.json and generates a migration SQL file that
 * recreates all triggers. Edit the JSON, run this script, commit, deploy.
 * 
 * Workflow:
 *   1. Edit prisma/triggers.json (change timing, table, function, add/remove)
 *   2. npx tsx scripts/sync-triggers.ts
 *   3. Commit the generated migration file
 *   4. Deploy: prisma migrate deploy
 * 
 * This makes trigger management dynamic -- change the JSON config,
 * the script generates the correct DROP + CREATE SQL automatically.
 */

import * as fs from 'fs';
import * as path from 'path';

interface TriggerDef {
    name: string;
    table: string;
    timing: 'BEFORE' | 'AFTER' | 'INSTEAD OF';
    events: string;
    function: string;
    when: string | null;
}

interface TriggersConfig {
    version: string;
    triggers: TriggerDef[];
}

function generateTriggerSql(t: TriggerDef): string {
    const drop = `DROP TRIGGER IF EXISTS ${t.name} ON "${t.table}";`;
    const when = t.when ? ` WHEN (${t.when})` : '';
    const create = `CREATE TRIGGER ${t.name}\n${t.timing} ${t.events} ON "${t.table}"\nFOR EACH ROW${when}\nEXECUTE FUNCTION ${t.function};`;
    return `${drop}\n${create}`;
}

function main() {
    const configPath = path.join(__dirname, '../prisma/triggers.json');
    
    if (!fs.existsSync(configPath)) {
        console.error('prisma/triggers.json not found. Create it first.');
        process.exit(1);
    }

    const config: TriggersConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    
    console.log(`Syncing ${config.triggers.length} triggers from config...\n`);

    // Generate migration timestamp
    const now = new Date();
    const pad = (n: number) => n.toString().padStart(2, '0');
    const ts = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
    const dirName = `${ts}_sync_trigger_definitions`;
    const outDir = path.join(__dirname, '../prisma/migrations', dirName);
    
    // Generate SQL
    const parts: string[] = [
        '-- Auto-generated by scripts/sync-triggers.ts',
        `-- Trigger config version: ${config.version}`,
        `-- Generated: ${now.toISOString()}`,
        '-- Drops and recreates all triggers from prisma/triggers.json',
        '',
    ];

    for (const t of config.triggers) {
        parts.push(`-- ${t.name} on ${t.table}`);
        parts.push(generateTriggerSql(t));
        parts.push('');
        console.log(`  ${t.name} -> ${t.table} (${t.timing} ${t.events})`);
    }

    const sql = parts.join('\n');

    // Write migration file
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, 'migration.sql'), sql);

    console.log(`\n  Written: prisma/migrations/${dirName}/migration.sql`);
    console.log(`  ${config.triggers.length} triggers defined.`);
    console.log('\n  Next: Commit this migration file, then deploy.');
}

main();
