-- Auto-generated by scripts/sync-triggers.ts
-- Trigger config version: 1.0
-- Generated: 2026-08-13T07:33:04.923Z
-- Drops and recreates all triggers from prisma/triggers.json

-- trg_pre_erp_auto_calc on PreErpMaterialBalance
DROP TRIGGER IF EXISTS trg_pre_erp_auto_calc ON "PreErpMaterialBalance";
CREATE TRIGGER trg_pre_erp_auto_calc
BEFORE INSERT OR UPDATE ON "PreErpMaterialBalance"
FOR EACH ROW
EXECUTE FUNCTION fn_pre_erp_auto_calc();

-- trg_prevent_negative_stock on InventoryStock
DROP TRIGGER IF EXISTS trg_prevent_negative_stock ON "InventoryStock";
CREATE TRIGGER trg_prevent_negative_stock
BEFORE INSERT OR UPDATE ON "InventoryStock"
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_negative_stock();

-- trg_auto_ledger_checksum on InventoryLedger
DROP TRIGGER IF EXISTS trg_auto_ledger_checksum ON "InventoryLedger";
CREATE TRIGGER trg_auto_ledger_checksum
BEFORE INSERT ON "InventoryLedger"
FOR EACH ROW
EXECUTE FUNCTION fn_auto_ledger_checksum();

-- trg_cycle_count_variance on CycleCountLine
DROP TRIGGER IF EXISTS trg_cycle_count_variance ON "CycleCountLine";
CREATE TRIGGER trg_cycle_count_variance
BEFORE INSERT OR UPDATE ON "CycleCountLine"
FOR EACH ROW
EXECUTE FUNCTION fn_calc_cycle_variance();

-- trg_low_stock_auto_alert on InventoryStock
DROP TRIGGER IF EXISTS trg_low_stock_auto_alert ON "InventoryStock";
CREATE TRIGGER trg_low_stock_auto_alert
AFTER UPDATE ON "InventoryStock"
FOR EACH ROW WHEN (NEW.quantity <= NEW."minLevel" AND OLD.quantity > OLD."minLevel")
EXECUTE FUNCTION fn_notify_low_stock();

-- trg_wastage_limit_check on ContractorWastageItem
DROP TRIGGER IF EXISTS trg_wastage_limit_check ON "ContractorWastageItem";
CREATE TRIGGER trg_wastage_limit_check
BEFORE INSERT ON "ContractorWastageItem"
FOR EACH ROW
EXECUTE FUNCTION fn_validate_wastage_limit();

-- trg_variance_adjustment_calc on MaterialVarianceAdjustment
DROP TRIGGER IF EXISTS trg_variance_adjustment_calc ON "MaterialVarianceAdjustment";
CREATE TRIGGER trg_variance_adjustment_calc
BEFORE INSERT OR UPDATE ON "MaterialVarianceAdjustment"
FOR EACH ROW
EXECUTE FUNCTION fn_calc_variance_adjustment();
